version: '3.7'

services:
    app:
        container_name: sf5_app
        build:
            context: ./docker/app
            dockerfile: Dockerfile
            args:
                APP_ENV: ${APP_ENV}
                PHP_VERSION: ${PHP_VERSION}
                PROJECT_ROOT: ${PROJECT_ROOT}
                TIMEZONE: ${TIMEZONE}
        env_file:
            - .env
        environment:
            XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}
            PHP_IDE_CONFIG: serverName=${NGINX_HOST}
        volumes:
            - ./app:${PROJECT_ROOT}:rw,cached

    nginx:
        container_name: sf5_nginx
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
            args:
                NGINX_VERSION: ${NGINX_VERSION}
                NGINX_HOST: ${NGINX_HOST}
        env_file:
            - .env
        ports:
            - 8008:80
            - 443:443
        volumes:
            - ./app/public:${PROJECT_ROOT}/public:ro
            - ./docker/nginx/conf/default_template.cnf:/etc/nginx/conf.d/default.template
            - ./log/nginx:/var/log/nginx
        depends_on:
          - app
        command: /bin/bash -c "envsubst '$$NGINX_HOST $$PROJECT_ROOT'
            < /etc/nginx/conf.d/default.template
            > /etc/nginx/conf.d/default.conf
            && exec nginx -g 'daemon off;'"

    database:
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports: [5432]

volumes:
    log.nginx:
    .certs:
