version: '3.7'

services:
    app:
        container_name: sf5_app
        build:
            context: ./docker/app
            dockerfile: Dockerfile
            args:
                APP_ENV: ${APP_ENV}
                PHP_VERSION: ${PHP_VERSION}
                PROJECT_ROOT: ${PROJECT_ROOT}
                TIMEZONE: ${TIMEZONE}
                CHROME_VERSION: '80'
                CHROMEDRIVER_VERSION: '80.0.3987.106'
        env_file:
            - .env
        environment:
            XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}
            PHP_IDE_CONFIG: serverName=${NGINX_HOST}
        volumes:
            - ./app:${PROJECT_ROOT}:rw,cached
        depends_on:
            - database

    nginx:
        container_name: sf5_nginx
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
            args:
                NGINX_VERSION: ${NGINX_VERSION}
                NGINX_HOST: ${NGINX_HOST}
        env_file:
            - .env
        ports:
            - 8008:80
            - 443:443
        volumes:
            - ./app/public:${PROJECT_ROOT}/public:ro
            - ./docker/nginx/conf/default_template.cnf:/etc/nginx/conf.d/default.template
            - ./log/nginx:/var/log/nginx
        depends_on:
          - app
        command: /bin/bash -c "envsubst '$$NGINX_HOST $$PROJECT_ROOT'
            < /etc/nginx/conf.d/default.template
            > /etc/nginx/conf.d/default.conf
            && exec nginx -g 'daemon off;'"

    database:
        image: postgres:11-alpine
        volumes:
            - db-data:/var/lib/postgresql/data/sf5_book_data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /var/lib/postgresql/data/sf5_book_data
        ports:
            - 32849:5432

    redis:
        image: redis:5-alpine
        ports: [6379]
        volumes:
            - ./.data/redis:/data

    rabbitmq:
        image: rabbitmq:3.7-management
        hostname: rabbitmq
        user: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./.data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
        environment:
            RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq
            RABBITMQ_DEFAULT_VHOST: /

volumes:
    db-data:
    log.nginx:
    .certs:
#    .db: {}
