easy_admin:
    site_name: Conference Guestbook

    design:
        menu:
            - { route: 'homepage', label: 'Back to the website', icon: 'home'  }
            - { entity: 'Conference', label: 'Conferences', icon: 'map-marker'  }
            - { entity: 'Comment', label: 'Comments', icon: 'comments'  }

    entities:
        Conference:
            class: App\Entity\Conference
            list:
                fields:
                    - id
                    - slug
                    - city
                    - year
                    - isInternational
                    - comments

        Comment:
            class: App\Entity\Comment
            list:
                fields:
                    - author
                    - { property: 'email', type: 'email' }
                    - { property: 'photoFilename', type: 'image', 'base_path': '/uploads/photos', label: 'Photo' }
                    - { property: 'createdAt', type: 'datetime' }
                sort: ['createdAt', 'ASC']
                filters: ['conference']
            edit:
                fields:
                    - { property: 'conference' }
                    - { property: 'createdAt', type: 'datetime', type_options: { attr: { readonly: true } } }
                    - { property: 'author' }
                    - { property: 'email', type: 'email' }
                    - text
