name: Static code analysis
# event that trigger the execution of the action (can by multiple)
on:
    push:
        branches:
            - master
#            - features/*
    pull_request:
        branches:
            - master

jobs:
    static-code-analysis:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            -   name: Validate composer.json and composer.lock
                working-directory: ./app
                run: composer validate

            - name: Install composer dependencies
              working-directory: ./app
              run: |
                  composer install --no-ansi --no-interaction --no-suggest --prefer-dist
                  composer require phpstan/phpstan

            - name: Run PHPStan
              working-directory: ./app
              run: |
                  php vendor/bin/phpstan analyze -c phpstan.neon src tests --level 7
